services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: kitchenowl
      POSTGRES_USER: kitchenowl
      POSTGRES_PASSWORD: example
    volumes:
      - ./kitchenowl_db:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    ports:
      - "9090:8080"
    networks:
      - default
    environment:
      JWT_SECRET_KEY: PLEASE_CHANGE_ME
      DB_DRIVER: postgresql
      DB_HOST: db
      DB_NAME: kitchenowl
      DB_USER: kitchenowl
      DB_PASSWORD: example
    depends_on:
      - db
    volumes:
    - ./kitchenowl_files:/data

networks:
  default: